#!/usr/bin/env python3
"""Inject the generated SEO block into index.html.

index.html is the one hand-authored page, so its canonical/Open Graph/schema
block is written between markers rather than assembled at build time. Run this
whenever site_config.py or the FAQ copy changes:

    python3 print_home_head.py && python3 apply_home_head.py

It replaces everything between <!-- SEO:START --> and <!-- SEO:END --> with the
output of print_home_head(), so the homepage can never drift from the location
pages on canonicals, Open Graph defaults or the business schema.
"""

import pathlib
import re
import sys

import print_home_head as gen

ROOT = pathlib.Path(__file__).resolve().parent
INDEX = ROOT / "index.html"

START = "<!-- SEO:START"
END = "<!-- SEO:END -->"


def main() -> None:
    html = INDEX.read_text(encoding="utf-8")

    meta = gen.seo.head_meta(url=gen.URL, title=gen.TITLE, description=gen.DESC)
    ld = gen.seo.graph(
        gen.seo.business_node(page_url=gen.URL),
        gen.seo.website_node(),
        gen.seo.web_page_node(url=gen.URL, title=gen.TITLE, description=gen.DESC),
        gen.seo.faq_node(url=gen.URL, faqs=gen.FAQS),
    )

    block = "\n".join([
        "<!-- SEO:START — generated by print_home_head.py + apply_home_head.py.",
        "     Edit site_config.py / print_home_head.py and re-run, do not hand-edit. -->",
        meta,
        gen.seo.favicon_links(""),
        "",
        '  <script type="application/ld+json">',
        ld,
        "  </script>",
        "  <!-- SEO:END -->",
    ])

    pattern = re.compile(
        re.escape("<!-- SEO:START") + r".*?" + re.escape(END),
        re.S,
    )
    if not pattern.search(html):
        sys.exit("SEO markers not found in index.html")

    updated = pattern.sub(lambda _: block, html, count=1)
    INDEX.write_text(updated, encoding="utf-8")
    print(f"updated {INDEX}")
    print(f"  meta block: {len(meta):,} chars")
    print(f"  json-ld:    {len(ld):,} chars")


if __name__ == "__main__":
    main()